//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dungeon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dungeonEntities : DbContext
    {
        public dungeonEntities()
            : base("name=dungeonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lvl_Up> Lvl_Up { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Masters> Masters { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<SeansTicket> SeansTicket { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Client> Client { get; set; }
    }
}
