//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dungeon
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeansTicket
    {
        public int Id { get; set; }
        public string Price { get; set; }
        public string Number_Of_Visits { get; set; }
        public string Type_Of_Service { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MasterId { get; set; }
    
        public virtual Masters Masters { get; set; }
        public virtual User User { get; set; }
    }
}
